### ISSUE TITLE
heartbeat plugin needs update for EOSIO 2.0.0

### ISSUE THREAD

**Issue by matthewdarwin** [bancorprotocol/eos-producer-heartbeat-plugin#9]
heartbeat plugin fails to build on 2.0.0.-rc1

```
/tmp/build.31911/eos/plugins/producer_heartbeat_plugin/producer_heartbeat_plugin.cpp:68:41: error: no viable conversion from 'const char [1]' to 'eosio::chain::account_name' (aka 'eosio::chain::name')
      account_name heartbeat_contract = "";
                                        ^~
/tmp/build.31911/eos/libraries/chain/include/eosio/chain/name.hpp:43:11: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'const char [1]' to
      'const eosio::chain::name &' for 1st argument
   struct name {
          ^
/tmp/build.31911/eos/libraries/chain/include/eosio/chain/name.hpp:43:11: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'const char [1]' to 'eosio::chain::name &&'
      for 1st argument
/tmp/build.31911/eos/plugins/producer_heartbeat_plugin/producer_heartbeat_plugin.cpp:69:51: error: no viable conversion from 'const char [1]' to 'eosio::chain::account_name' (aka 'eosio::chain::name')
      account_name heartbeat_blacklist_contract = "";
                                                  ^~
/tmp/build.31911/eos/libraries/chain/include/eosio/chain/name.hpp:43:11: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'const char [1]' to
      'const eosio::chain::name &' for 1st argument
   struct name {
          ^
/tmp/build.31911/eos/libraries/chain/include/eosio/chain/name.hpp:43:11: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'const char [1]' to 'eosio::chain::name &&'
      for 1st argument
/tmp/build.31911/eos/plugins/producer_heartbeat_plugin/producer_heartbeat_plugin.cpp:149:33: error: no matching constructor for initialization of 'vector<eosio::chain::permission_level>'
            act.authorization = vector<permission_level>{{producer_name,heartbeat_permission}};
                                ^                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:502:40: note: candidate constructor not viable: cannot convert initializer list argument to 'const std::__1::vector<eosio::chain::permission_level,
      std::__1::allocator<eosio::chain::permission_level> >::allocator_type' (aka 'const std::__1::allocator<eosio::chain::permission_level>')
    _LIBCPP_INLINE_VISIBILITY explicit vector(const allocator_type& __a)
                                       ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:514:14: note: candidate constructor not viable: cannot convert initializer list argument to 'std::__1::vector<eosio::chain::permission_level,
      std::__1::allocator<eosio::chain::permission_level> >::size_type' (aka 'unsigned long')
    explicit vector(size_type __n);
             ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:558:5: note: candidate constructor not viable: cannot convert initializer list argument to 'const std::__1::vector<eosio::chain::permission_level,
      std::__1::allocator<eosio::chain::permission_level> >'
    vector(const vector& __x);
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:565:5: note: candidate constructor not viable: no known conversion from 'eosio::chain::account_name' (aka 'eosio::chain::name') to
      'eosio::chain::permission_level' for 1st argument
    vector(initializer_list<value_type> __il);
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:571:5: note: candidate constructor not viable: cannot convert initializer list argument to 'std::__1::vector<eosio::chain::permission_level,
      std::__1::allocator<eosio::chain::permission_level> >'
    vector(vector&& __x)
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:521:9: note: candidate constructor template not viable: requires 2 arguments, but 1 was provided
        vector(_InputIterator __first,
        ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:529:9: note: candidate constructor template not viable: requires at least 3 arguments, but 1 was provided
        vector(_InputIterator __first, _InputIterator __last, const allocator_type& __a,
        ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:536:9: note: candidate constructor template not viable: requires 2 arguments, but 1 was provided
        vector(_ForwardIterator __first,
        ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:543:9: note: candidate constructor template not viable: requires at least 3 arguments, but 1 was provided
        vector(_ForwardIterator __first, _ForwardIterator __last, const allocator_type& __a,
        ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:496:5: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
    vector() _NOEXCEPT_(is_nothrow_default_constructible<allocator_type>::value)
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:516:14: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    explicit vector(size_type __n, const allocator_type& __a);
             ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:518:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(size_type __n, const value_type& __x);
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:559:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(const vector& __x, const allocator_type& __a);
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:568:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(initializer_list<value_type> __il, const allocator_type& __a);
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:579:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(vector&& __x, const allocator_type& __a);
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:519:5: note: candidate constructor not viable: requires 3 arguments, but 1 was provided
    vector(size_type __n, const value_type& __x, const allocator_type& __a);
    ^
/tmp/build.31911/eos/plugins/producer_heartbeat_plugin/producer_heartbeat_plugin.cpp:169:45: error: no matching constructor for initialization of 'vector<eosio::chain::permission_level>'
                     act_bl.authorization = vector<permission_level>{{producer_name,heartbeat_permission}};
                                            ^                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:502:40: note: candidate constructor not viable: cannot convert initializer list argument to 'const std::__1::vector<eosio::chain::permission_level,
      std::__1::allocator<eosio::chain::permission_level> >::allocator_type' (aka 'const std::__1::allocator<eosio::chain::permission_level>')
    _LIBCPP_INLINE_VISIBILITY explicit vector(const allocator_type& __a)
                                       ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:514:14: note: candidate constructor not viable: cannot convert initializer list argument to 'std::__1::vector<eosio::chain::permission_level,
      std::__1::allocator<eosio::chain::permission_level> >::size_type' (aka 'unsigned long')
    explicit vector(size_type __n);
             ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:558:5: note: candidate constructor not viable: cannot convert initializer list argument to 'const std::__1::vector<eosio::chain::permission_level,
      std::__1::allocator<eosio::chain::permission_level> >'
    vector(const vector& __x);
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:565:5: note: candidate constructor not viable: no known conversion from 'eosio::chain::account_name' (aka 'eosio::chain::name') to
      'eosio::chain::permission_level' for 1st argument
    vector(initializer_list<value_type> __il);
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:571:5: note: candidate constructor not viable: cannot convert initializer list argument to 'std::__1::vector<eosio::chain::permission_level,
      std::__1::allocator<eosio::chain::permission_level> >'
    vector(vector&& __x)
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:521:9: note: candidate constructor template not viable: requires 2 arguments, but 1 was provided
        vector(_InputIterator __first,
        ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:529:9: note: candidate constructor template not viable: requires at least 3 arguments, but 1 was provided
        vector(_InputIterator __first, _InputIterator __last, const allocator_type& __a,
        ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:536:9: note: candidate constructor template not viable: requires 2 arguments, but 1 was provided
        vector(_ForwardIterator __first,
        ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:543:9: note: candidate constructor template not viable: requires at least 3 arguments, but 1 was provided
        vector(_ForwardIterator __first, _ForwardIterator __last, const allocator_type& __a,
        ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:496:5: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
    vector() _NOEXCEPT_(is_nothrow_default_constructible<allocator_type>::value)
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:516:14: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    explicit vector(size_type __n, const allocator_type& __a);
             ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:518:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(size_type __n, const value_type& __x);
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:559:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(const vector& __x, const allocator_type& __a);
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:568:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(initializer_list<value_type> __il, const allocator_type& __a);
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:579:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(vector&& __x, const allocator_type& __a);
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/vector:519:5: note: candidate constructor not viable: requires 3 arguments, but 1 was provided
    vector(size_type __n, const value_type& __x, const allocator_type& __a);
    ^
/tmp/build.31911/eos/plugins/producer_heartbeat_plugin/producer_heartbeat_plugin.cpp:185:40: error: no viable conversion from 'eosio::chain::packed_transaction' to 'const chain::packed_transaction_ptr'
      (aka 'const shared_ptr<eosio::chain::packed_transaction>')
            plugin.accept_transaction( packed_transaction(trx),[=](const fc::static_variant<fc::exception_ptr, transaction_trace_ptr>& result){
                                       ^~~~~~~~~~~~~~~~~~~~~~~
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/memory:3757:23: note: candidate constructor not viable: no known conversion from 'eosio::chain::packed_transaction' to 'std::nullptr_t' (aka 'nullptr_t') for 1st
      argument
    _LIBCPP_CONSTEXPR shared_ptr(nullptr_t) _NOEXCEPT;
                      ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/memory:3771:5: note: candidate constructor not viable: no known conversion from 'eosio::chain::packed_transaction' to
      'const std::__1::shared_ptr<eosio::chain::packed_transaction> &' for 1st argument
    shared_ptr(const shared_ptr& __r) _NOEXCEPT;
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/memory:3779:5: note: candidate constructor not viable: no known conversion from 'eosio::chain::packed_transaction' to
      'std::__1::shared_ptr<eosio::chain::packed_transaction> &&' for 1st argument
    shared_ptr(shared_ptr&& __r) _NOEXCEPT;
    ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/memory:3774:9: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'eosio::chain::packed_transaction'
        shared_ptr(const shared_ptr<_Yp>& __r,
        ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/memory:3780:52: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'eosio::chain::packed_transaction'
    template<class _Yp> _LIBCPP_INLINE_VISIBILITY  shared_ptr(shared_ptr<_Yp>&& __r,
                                                   ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/memory:3799:9: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'eosio::chain::packed_transaction'
        shared_ptr(unique_ptr<_Yp, _Dp>&&,
        ^
/local/lib/eosio-2.0/opt/clang8/include/c++/v1/memory:3808:9: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'eosio::chain::packed_transaction'
        shared_ptr(unique_ptr<_Yp, _Dp>&&,
        ^
/tmp/build.31911/eos/plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp:709:65: note: passing argument to parameter 'trx' here
   void accept_transaction(const chain::packed_transaction_ptr& trx, chain::plugin_interface::next_function<chain::transaction_trace_ptr> next);
                                                                ^
/tmp/build.31911/eos/plugins/producer_heartbeat_plugin/producer_heartbeat_plugin.cpp:347:28: error: no viable overloaded '='
         my->producer_name = ops[0];
         ~~~~~~~~~~~~~~~~~ ^ ~~~~~~
/tmp/build.31911/eos/libraries/chain/include/eosio/chain/name.hpp:43:11: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'const
      std::__1::__vector_base<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >::value_type' (aka 'const std::__1::basic_string<char>') to 'const eosio::chain::name' for 1st argument
   struct name {
          ^
/tmp/build.31911/eos/libraries/chain/include/eosio/chain/name.hpp:43:11: note: candidate function (the implicit move assignment operator) not viable: no known conversion from 'const
      std::__1::__vector_base<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >::value_type' (aka 'const std::__1::basic_string<char>') to 'eosio::chain::name' for 1st argument
6 errors generated.
plugins/producer_heartbeat_plugin/CMakeFiles/producer_heartbeat_plugin.dir/build.make:62: recipe for target 'plugins/producer_heartbeat_plugin/CMakeFiles/producer_heartbeat_plugin.dir/producer_heartbeat_plugin.cpp.o' failed
make[2]: *** [plugins/producer_heartbeat_plugin/CMakeFiles/producer_heartbeat_plugin.dir/producer_heartbeat_plugin.cpp.o] Error 1
make[2]: Leaving directory '/tmp/build.31911/eos/build'
CMakeFiles/Makefile2:5058: recipe for target 'plugins/producer_heartbeat_plugin/CMakeFiles/producer_heartbeat_plugin.dir/all' failed
make[1]: *** [plugins/producer_heartbeat_plugin/CMakeFiles/producer_heartbeat_plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
